language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/backend.jar -t $DOCKER_USERNAME/se234-lab10-backend
  .
- docker push $DOCKER_USERNAME/se234-lab10-backend
- docker pull $DOCKER_USERNAME/se234-lab10-client
script:
- docker-compose -H "$DOCKER_HOST" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: mXM1J20BxjV/0E+PjSVhZXOZCCcPNl4ZIbN2NCvcHOP5ksy2phaDw5VqcIdk3bHqDcHkcaYOBGvuAYnxXUpsDOOPEWR/xDiYPcjeeHd0G3mWJj8hYXdP9iBYENxNLp6Yll114zXoapXrsRU9np8P7V39Cd7za7+6ILbC8m/bw49nmpw6rExZ2fORM98v57F5Cv9wNlb8yk53yn+eP+PvEg+e9JFGUXPlk6GbIMISoX37pm5nXZfqpVClsxE4HBJWgNs4btWkG9Pwss8jTkCP1LBIDUiqxByI51WmVJLE/obw8azVOYnZYahxOtpx1KZM5F3OigX6VLugIwLV4Q6DSOw35E0/V6J+/NefWfNC5TVTrsgYnGOBVefn6aTlTq4qSMDmgTFeSg0RredE+LKRJ3qfq+Tfbc00J4eMrQgBTnIGJaHBSIor41HLtEm08LHCmUEAFz0CNuUVuWn7Y87lSUhMv+/0q4r90s0W8ZaclCUGoQxXJnn4x5VoAqprrHV2+x8O+bXJLpk7xEsT0YGlCIjiT4KzgfECRIkZmmvsIMTbmbHdlDlQIzufbTvdv9UTz+90bdg9hjtQljAVRhEx9tQ/lsBOOEC0FOLzrgPnPLclS48Tz5b0dkdYBxw290hkrIBc7eIGsI8PHtzltRhZvMQfgob26Zof1HtmYBTJEwQ=
  - secure: elcvNzCyack+YTs3YVWuDn3k71AH8E7thpA5Iah0LXPaiUptcAtoyiTxBXz5wIOVoioF6bYv5UzyXge4lAfn0whX1qW9xSaciClcq5FcdJkwG9re8uyAnGx2EZsh8IsU9tkMyrtd6rTwxtKN2DOwlZVhGdsPTXyMb2xXeb2sXVuXa4iXX9zBSZcytAnQ9AUT5d97yl1UuX+Y965LSNeNOPKS6//reBUck5rqVdNMvlSexbHkRP/PUSWa8vZUtMXlKIXCA6rLbWTYe9Ubx4unVWO/d4e3bnRsYkRkteAz2NjXJGq+YwQe9R+rd1tkegvC7f8PQcf6MoVbEqRGOplBqhC9EuuZwJgvHh9re/4qvHKBErKjNJX2j4WNciNrbgqCSYy7oJZIvMx6D2BXgo3cL99r72+GhsVlM2HCcd1qyGLgaS0EwTimx+L3ygdjMLok6KTS5pJt6+wdtPeCvqDovtt4K9CXQHNlpI2ijLV5n+aw+W1xHQxp/n6oG5sLiDtK2F2AMYVajBJaiOBdrTfa6Q5tVZ5TNzn5WvhYjTN0cwnztsRrDTSVOM7BQlxgclFs+5zPVY8RoH6DKpmL60k6rEWBVnhceI5j8P5ax+EMyg381t2YRLtifL4hAiKe61uUtdjeHQZdwfUOAV7D1keiAipRW1UmgqdGDbojz7yAjAI=
  - secure: ifOQkoOEMOPRsZRQwap/Pua9Xl+wTkVPLTCioU2APEp8K8R6+DV2PrYYbGOJTEaJOWPKjMUDIMqx3rMijIL3N1nDYPXkGP9cyUZRHA4TbKNRj3ZmbOtuY4sRUuHG+0BmgsSCcL0XO7jfu1MPSPBKbVZOU66vHcc9z6mERwL/uBkNW/aDxDuaRq6NBkBrRBzMU/AJwEl3/RZ0i1ut5TyEHrSLT0EQJ02kc+8xIvXtvfcHRCAmd1X4JmU3mkv4Qy6HV1WjH+r9tZFPxma6tfh8ZOKVc35RbqtWs/p+Ac+75VNMw+dYRJguUb7J3tns04+k/e6rXavHgxD2B8EJtYtXzyRwszKkrK4EQurbt2b02ws3s2I9arHeDbbGT+zdvGqEEpu9r2gxZuXS8G+AB5YaxxbfHXEz964/pwMh7MSoPaTFMCPV2/oO+7wnWB0d5Lr3nnszgX4ExQTjspp7m/BVUdzJxMnnCPkU77Rof6thlKw2mTvqZSSBIDBFSIDA84CFpsGVy3NYDT0LIG1K9ufLaP0Vs1ZAr6aKLs0YHttS9qRuu0lCaBlHJjIOjJFB2YQf8HAznyRC9feAXJuFiAVomTtYG+woZqYOAoqwtqMzx2ivtqOm26lVRO5DPqYgRM1O/86db3OZJNtpkoCnmED0WUdgg09soT1Yo6mTswgriMs=
  