language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/backend.jar -t $DOCKER_USERNAME/se234-lab10-backend
  .
- docker push $DOCKER_USERNAME/se234-lab10-backend
- docker pull $DOCKER_USERNAME/se234-lab10-client
script:
- docker-compose -H "$DOCKER_HOST" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: mS6vy4p95mnknurvoEThjrZ16S9Cb+m9xyZdr+GTu7RaBSMuno+1eqrUPT3tcN4qyNLfk5u44r1CVK5FkMJ8b6xz8pIe7i5LmMEq5xef1dd79QXzEG7HQuLq/Y3e6CMwWICLXaHqdJvled6lvYBjBOFyGfsx2vNkofiE0btZlh54R4nCu+K/pZcs9WjziUswTfKrBNTYddl++5KuweaQkhKPXswAm/gd1nZG1WSZpvCo4HHPSCrTQR6HRV02xkav6npG2+S+NjN+Qk63K1HamrXpSTVUqwINuAbqH5VFQH5klfgEFWIRrF8gU8uygWP9OGlw7QfZNXG2LcQfS+4oI4S0ztCk9dpMXvh4epi53TmFMcyJpu6/mceu0A8AGTwzqvsWVlvIKUxI2Ktgsg9vLKg5Ig42+w+DXaaDJGEm9G8UfVWQje3WAfxsV8b8h8Nl4QDoHuIFEn80LaAnAu953o1JvdPjWH73gk2PN82VHzNLmqAjBzluigUddgk66JHKGn3BK0k4aghgXgagC+Nxt2QoRyDeoi7NDbrTQMysBwr2YAQxEKA4jQVP/Loi9NB8LdGOsY6c5ZqPj2RQaQNh4UFneOVdQp9ASPAjevJVHcwKzaoKC5qTb/gqQb1tbOCcklWL6eclI/NWCXMiUr8hHGL/cc4wSEvN/CTrFFgEqzE=
  - secure: WqKuaIO20M/aLkSLlvINCS8c6AHC62I1IXIme7E+NrPBU1DYjJu1LmW94LA9SYoOEzfmCwN5M5LM8xLqasTVxsYaYmfVZZgCSedQir19zKxijGp9/nMfC/nTq//z3k1Dg8yv8shmXLClUoCCNwxp9uCVGabVrIYt9jxqxf4oGcQYxzfU4er/F2BD+XTFzk2ZvHTR9oXtKx0FXFFEaaWPA5yFECUEWgo+WuRmoQGuWB1zGR/FQg3S9NzwnJEL4tVuOTesPvkoiOQjq05ESk+E1v9MmumymDtOxQhksyvWT8jt8jiqCBdN/zf35TGkk1n5l0x6+jIBpzuEUOV7uGRW7BDjJLzf4hr6CbJI8K1Gs7tQ+pDz0SUxOP0xKH+1knsxfmfaPSA3rx4XIb4I8tkPEoFbhl9ckW7UxDnehBMFxbwZ2Lp6oGApDTnJ8p0dyfRk9N1y/G5LXGZ22uJEzqKB7o0AL67s0vJ27kOJp55d6ZUnOkzGTRAX5dCyVEp2eTvOBKeQk7ziHZFNBW3WXG5H01FFQUQ/DzJGNTf3W7w+a/5HEFtVDQs0J9rij2QLrI+NjXzkhm/T/jwufn6gjaFKWRTHLRIuNgF4RHRB7wpwmatskeWFqFx62i0dUnNfn9WoBRlo/aLMXVbGnXEqFJ7Oj25XPybq9wiTX/LeECVKEGU=
  - secure: p6G2b+x1nVp2q8b5U0gh4qNp/7WkJkSsBDAZtHfAgMV5yi2LfGFWSA3/FJZTTbTbUCqwjqSoUqXj/McHxR/djtveje/uUl3ea3OtQEGWIw15xcUHDlNWPNZG0EZm1LabZiwtbiUHVtNYY124p5gGPg2TbuYAhMtMDMHMI3Y6ZbVxFuzo/aAaDDgEHJpHGQ53Rf5ObpqTupnR0+QDZfgB3jQijysQpWiBmVhEtsgsNmbDBgseQLepAFchBUisRCQWMCMYBciv8I8XrbwQlmQRXQpGQagVP1ny+u5HEmCacCPFVs26L0C2OmT79YKxtiCh6r3o6lB/wW0PyBJh9pNKjAEcMlM1UluYcMD/3wBOaTmln5qT4BkniCYvejc8eYFgxgkb4EzY5X1lD2AGvzq48RFzhSTLEwR315jKFcHPQCnP8nqjDYUgw7vcOC1XNLJWDBk/NQ9jkMDK8echlIO8fpTfv0EQyaKmcxht6PQZl8+jjn3Dspy9P7bkHF+3Nfeg+7hzdGPFw83xIOBC/5O3VeaEbOXL+BsQ5iwlecnhX+clH0qXVutwbGpL+X0kzDt6KmwDmQ+qCC5LEgbzorMjpb/sPSNBJA9KfX+x/ongCYfR0buh5Ghu2NsPBhfPZwfxgJCtOTyvsmSM5R90Yo4zyceCrxnfupZjzv8aM6ooCBM=
