language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "tititity" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/lab10-backend.jar -t $DOCKER_USERNAME/se234-lab10-backend
  .
- docker push tititity/se234-lab10-backend
- docker pull tititity/se234-lab10-client
script:
- docker-compose -H "$DOCKER_HOST" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: U87yGfzCs9gNLe9Aauz1e3TBpH1CZdsMfZzS3ONHFk/068uLTTtjPiZJxpLtL2U3b1qegCJFYLo2RlYv4bk20o9fQvYwB5ZTAGkQU6ZrggbhiGvpoD4dc6z4bF6lpGqOMvyCgxg0137Zp95qDnlaFB2Mz0bTiQ/jRiPJwqdmQWzjPaPKJctegZpuR2tzX7cnznFelE16zrJFjAK4c5oGFMBVubT7bUEmrv85aQxK5YfLTwxai/tmDQqVZTuwQaHIhLNrOCp4EcKQIzbtETz3zAAHT7Lj8HQsQ2Y7/jMg5ZkZGaG4af3b+YWRL5vS3fkWwuk4mHLP2b7IfcOGZrM3MX4C0XcQi/wHIrzVorNj2NWzdaxpAM7mFWj/QVSSVhWa9YvZpv9bMWnpl+lJFseaADgAT+K1vpSh1Hjy/e20jnIKrqB9J4cfkuMxRSAPNExBHNWoUlLxWJLvDGkVSZmJK563Z85OuOqRuzYZAvTJPwD5f6NoSsw7/TmbwdaeL4SlDKmmQV92EqkoJ8p8ffp+Yvq2frm1DpxTDqwVPwKYb73kabh58A9D6w+y+ZCyMgTpsv/W7/6KXRLnbsTtlkbCwGpSJ997pfuQQyCLqwkd6VtLOHaSK++INXbh8PdKA6rJ73wzgrV7L8BD+Al0jQh4mbZRVMXtqHWVEskXT2dWoLc=
  - secure: Pa/1nX04aDHmX8It5n/Y8xKgCEdUbmgm/KxBH7i0ubloQe3g8CjVsfwG0vYz953JnUD/9s5Uxwt5IKdW1K+WGKhqzDrfkYD5MZ8jsyuLs2fEfQLquTxICqhbJ9KDcCqvxg795FrNVjGvmcZ/1R1XZ4Sx1kLgd3cbOlJSg9ckk1vG9hfz7qjpAToodo9BlBDLQmGmZzeYd1K2GPo93stHD/lUz4o/OS3UQNwj8ygar3kl1prS8/kw5ZDkNxbmYlhBmm/97KjMXz34JOTWgeathOcDdEm5Of0c6VecbKLC7MTbP1L+JHsHmdXo9P28S8Ax0JST8R4c238AsgMIk3HuZUaB6d0Y2p3ZVLzTn6lGDcicL9w4b9ldpYmpojf47+9Gk7Ao0otuugNp3hsXkFF1wvKB41RP3D8/ebqKYkI6tzqqqoq15wSJmQUBYV3ogqHvWBxq+OvM/d89L/YtTFcDS6GTzz3I1wTDr8UdDJ07dyK0AObcZiwCXyHu7i/yw2x+Q96/RSLauJaA9IB8js2/qzvzfBC0F5Ka+i7HskvSOT89YoVC2p2LXG0qGuM+oZOuc8lIgf+htdF9Xu7cy8O9t8lpoqKq/QCz81otYeNs7pGmN4now4z7T2OyZQZFsFw2XyMD9mrrQM/yDC9KxhsojtkFNRU3F9WB+tooF3+lPco=
